site_name: API-Go2Doc
site_url: https://example.com/
repo_url: https://github.com/rickey-alok/api-go2doc
repo_name: rickey-alok/api-go2doc
theme:
  name: material
  language: en
  logo: https://t4.ftcdn.net/jpg/03/22/95/69/360_F_322956978_9ESBVewTYdhSu9G6qf2JazX9tUsdh53g.jpg
  favicon: https://t4.ftcdn.net/jpg/03/22/95/69/360_F_322956978_9ESBVewTYdhSu9G6qf2JazX9tUsdh53g.jpg
  icon:
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    edit: material/pencil
    view: material/eye
    admonition:
      type: material/alert-box
  features:
    # - header.autohide
    # - navigation.top
    # - navigation.footer
    # - navigation.tabs
    # - navigation.tabs.stickey
    # - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.view
    - content.action.edit
  palette:
    - primary: custom
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

use_directory_urls: true
nav:
  - Home: index.md
  - API: API.md
  - Docs-as-Code:
      - VS-Code: Docs-as-Code/VS-Code.md
      - Git & GitHub: Docs-as-Code/Git-GitHub.md
      - Postman: Docs-as-Code/Postman.md
  - For writing API Docs:
      - Markdown: API Docs/Markdown.md
      - OpenAPI Specification: API Docs/OepnAPISpec.md
      - JSON: API Docs/JSON.md
      - cURL: API Docs/cURL.md
extra_css:
  - stylesheets/extra.css

extra:
  alternate:
    - name: English
      link: .
      lang: en
    - name: Français
      link: /fr/
      lang: fr
    - analytics:
      provider: google
      property: G-0STBM9BNC1
    - social:
        - icon: fontawesome/brands/github
          link: https://github.com/spaceship-prompt/spaceship-prompt
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/SpaceshipPrompt

  plugins:
    - git-authors
    - search:
        lang:
          - en
          - fr
    - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_search: true
    - redirects:
        redirect_maps:
          "docs/index.md": "docs/index.fr.md"
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: fr
          name: Français
          build: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  # - material.extensions.preview:
  #   sources:
  #     include:
  #       - ...
  #     exclude:
  #       - ...
  #   targets:
  #     include:
  #       - ...
  #     exclude:
  #       - ...

copyright: Copyright &copy; 2024 , Site Author -  <a href="https://www.linkedin.com/in/alok-ranjan-34817a17/">Alok Ranjan</a>
