site_name: ApiGo2Doc
site_url: https://example.com/
repo_url: https://github.com/rickey-alok/apigo2doc
repo_name: rickey-alok/apigo2doc
theme:
  name: material
  language: en
  logo: https://t4.ftcdn.net/jpg/03/22/95/69/360_F_322956978_9ESBVewTYdhSu9G6qf2JazX9tUsdh53g.jpg
  favicon: https://t4.ftcdn.net/jpg/03/22/95/69/360_F_322956978_9ESBVewTYdhSu9G6qf2JazX9tUsdh53g.jpg
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    edit: material/pencil
    view: material/eye
    annotation: material/star-four-points-circle
    admonition:
      type: material/alert-box
  features:
    # - header.autohide
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.stickey
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    # - content.action.view
    - content.action.edit
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  extra_css:
    - stylesheets/extra.css
use_directory_urls: true
nav:
  - Home: index.md
  - API: API.md
  - package_library: package_library.md
  - Docs-as-Code:
      - VS-Code: Docs-as-Code/VS-Code.md
      - Git & GitHub: Docs-as-Code/Git-GitHub.md
      - Postman: Docs-as-Code/Postman.md
  - For writing API Docs:
      - Markdown: API Docs/Markdown.md
      - OpenAPI Specification: API Docs/OepnAPISpec.md
      - JSON: API Docs/JSON.md
      - cURL: API Docs/cURL.md

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  alternate:
    - name: English
      link: .
      lang: en
    - name: Français
      link: ./fr/
      lang: fr
    - analytics:
      provider: google
      property: G-0STBM9BNC1
    - social:
        - icon: fontawesome/brands/github
          link: https://github.com/spaceship-prompt/spaceship-prompt
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/SpaceshipPrompt

  plugins:
    - info
    - git-authors
    - search:
        lang:
          - en
          - fr
    - minify:
      minify_html: true
    - i18n:
      default language: en
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_search: false
      languages:
        - locale: en
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
    - autorefs
    - mkdocstrings:
      handlers:
        python:
          import:
            - https://installer.readthedocs.io/en/stable/objects.inv

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # - material.extensions.preview:
  #   sources:
  #     include:
  #       - ...
  #     exclude:
  #       - ...
  #   targets:
  #     include:
  #       - ...
  #     exclude:
  #       - ...

copyright: Copyright &copy; 2016-2024 Martin Donath
